apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: epidemic-engine-phase1-run-
spec:
  pipelineRef:
    name: epidemic-engine-phase1
  params:
    - name: kafka-bootstrap
      value: "kafka-team05:9092"
    - name: input-topic
      value: "ds551-s26.team05.raw"
    - name: validated-topic
      value: "ds551-s26.team05.validated"
    - name: symptom-topic
      value: "ds551-s26.team05.symptom_reports"
    - name: clinic-topic
      value: "ds551-s26.team05.clinic_visits"
    - name: hospital-topic
      value: "ds551-s26.team05.hospital_admissions"
    - name: vaccination-topic
      value: "ds551-s26.team05.vaccination_records"
    - name: team-id
      value: "team05"
    - name: batch-size
      value: "5000"